FROM postgres:9.6

ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=efila
ENV PGDATA=/opt/fgh/data/system/postgres
ADD localtime /etc/localtime
VOLUME /opt/fgh/data  

EXPOSE 5432
  


