version: '3.2'
services:

    fgh-postgresql-db:
        build: 
            context: ./postgresql
        container_name: fgh-postgresql-db
        ports: 
            - "5432:5432"
        volumes:
            - type: volume
              source: postgresdatadb
              target: /opt/fgh/data
        restart: unless-stopped

networks:
  default:
    external:
      name: fgh-openmrs-docker-master_network

volumes:
  postgresdatadb:
